# Generated by Django 3.2.3 on 2021-08-27 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('outstanding_shares', models.IntegerField()),
                ('share_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('revenue', models.IntegerField()),
                ('expenses', models.IntegerField()),
                ('total_assets', models.IntegerField()),
                ('total_liabilities', models.IntegerField()),
                ('current_assets', models.IntegerField()),
                ('current_liabilities', models.IntegerField()),
                ('operating_cashflows', models.IntegerField()),
                ('capex', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
